---
dependency:
  name: galaxy
driver:
  name: default
platforms:
    - name: test-instance
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    destroy: destroy.yml
verifier:
  name: testinfra
