---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance-1
    # Add any variables specific to this platform that Terraform needs, e.g.,
    image: ubuntu:22.04
    # region: us-east-1
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    destroy: destroy.yml
verifier:
  name: testinfra
