---
# tasks file for .

- name: "Configuring apt"
  import_tasks: apt.yml

- name: "Installing docker"
  import_tasks: docker.yml

- name: "Installing runner"
  import_tasks: ci.yml
  tags: github

- name: "Install nginx"
  import_tasks: web.yml
