- name: Install nginx
  apt:
    update_cache: true
    name: nginx
    state: present
- name: Copy config
  copy:
    content: |
      server {
        listen {{ nginx_port }};
        location / {
          root /var/www/html;
        }
      }
    dest: /etc/nginx/nginx.conf
- name: Start nginx
  service:
    name: nginx
    state: started
# - name: "Nginx stop"
#   service:
#     name: nginx
#     state: stopped

# - name: Container Nginx
#   community.docker.docker_container:
#     name: nginx-container
#     state: started
#     recreate: true
#     image: nginx:1.28
#     published_ports:
#       - 80:80
#     volumes:
#       - /etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
